### PR TITLE
Renamed javascript folder

### PR DESCRIPTION
**Pull request by Zbysekz**

### CODE REVIEW

**Comment by Zbysekz** [comment]
@breznak can you help me with this? it reports conflicts but locally (in gitkraken & cmd line all fine) to these two files, these are node.js NVM package files that keeps dependencies... i just renamed the parent folder to better name

**Comment by breznak** [comment]
> t reports conflicts but locally (in gitkraken & cmd line all fine) to these two files, these are node.js NVM package files that keeps dependencies... i just renamed the parent folder  

I'll have a look, is this still relevant? There's some merge conflict now with the newer additions.

**Comment by Zbysekz** [comment]
> > t reports conflicts but locally (in gitkraken & cmd line all fine) to these two files, these are node.js NVM package files that keeps dependencies... i just renamed the parent folder
> 
> I'll have a look, is this still relevant? There's some merge conflict now with the newer additions.

Yes i can't get rid of these two files:
javascript/package-lock.json
javascript/package.json

i just wanted to rename this "javascript" folder to "objectVisualizer".
You have free hand, do whatever you want

**Comment by breznak** [comment]
@Zbysekz is this it? I resolved the merge. 
Also, your CI python build is failing (on detail) on syntax checks in `flake8` 
https://app.circleci.com/pipelines/github/htm-community/htm-2d-object-modeling/29/workflows/acc167ac-613b-47bb-bf89-c9539f989dea/jobs/56

**Comment by Zbysekz** [comment]
@breznak Nice this is it, thank you :) Yes i will take a look at the flake8, it's codestyle check

**Pull request merged**
