### PR TITLE
Py agent and env

### PR DESCRIPTION
**Pull request by Zbysekz**
Agent extended with 4 sensors; Environmnent extended, boundary checks; Unit tests included; Main.py file added with basic draft

### CODE REVIEW

**Comment by Zbysekz** [comment]
hmm i have some formatting problems, i am using spyder, don't know for now how to do autoformatting.

**Comment by rhyolight** [comment]
Great job! I can help you with the formatting. But you also need to add new dependencies (like numpy and htm.bindings) to the `pipenv` environment file `Pipfile`. You should run your `main.py` script with `pipenv run python main.py`.

Also, it would be nice to pull model parameters out into a config file(s) so we can easily try different parameter iterations.

**Comment by rhyolight** [comment]
Struggling to figure out the best way do python 3 dependencies, since `htm.bindings` is not installable from anywhere except source. I will try to set up a docker container for it and run there soon.

**Comment by Zbysekz** [comment]
Exactly i struggle also. I have successfuly installed pipenv, but when i try to build htm with command `pipenv install -e .` it fails on 100% on _file COPY cannot set permissions on
  "/home/osboxes/nupic.cpp/build/Release/distr/./tests/htmlcov"_

**Comment by Zbysekz** [comment]
Hmm permisions problem solved (i have used sudo to build htm previously) but another problem, probably what you say with the py3 dependencies... Ok i'll wait for the docker image

**Comment by rhyolight** [comment]
I am having issues running `pipenv` within docker. I'm still not convinced it is the best option. I might try standard `pip` with a `requirements.txt` file.

**Pull request merged**
